language: rust
sudo: required
dist: trusty
addons:
  apt:
    packages:
      - libssl-dev
cache: cargo
after_success: |
  RUSTFLAGS="--cfg procmacro2_semver_exempt" cargo install cargo-tarpaulin &&
  cargo tarpaulin --out Xml &&
  bash <(curl -s https://codecov.io/bash)
