language: rust
sudo: required
dist: trusty
addons:
  apt:
    packages:
      - libssl-dev
cache: cargo
before_cache:
  - RUSTFLAGS="--cfg procmacro2_semver_exempt" cargo install cargo-tarpaulin
after_success: |
  cargo tarpaulin --out Xml &&
  bash <(curl -s https://codecov.io/bash)
